// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzoQKRsZMhUODSbz9RRrfb3wKOyKCiqs',
    appId: '1:922332617982:web:cdeeb427b22f5e9b6659af',
    messagingSenderId: '922332617982',
    projectId: 'my-place-18dc3',
    authDomain: 'my-place-18dc3.firebaseapp.com',
    storageBucket: 'my-place-18dc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhIsWTf2fZLYYXJPkG3vzLWXbO93kKMz4',
    appId: '1:922332617982:android:fd5055bbd1e063a36659af',
    messagingSenderId: '922332617982',
    projectId: 'my-place-18dc3',
    storageBucket: 'my-place-18dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQSI_yLwHHl1EB4wRCX2NSOrP9rYy4AY',
    appId: '1:922332617982:ios:2dd82729c3efb5706659af',
    messagingSenderId: '922332617982',
    projectId: 'my-place-18dc3',
    storageBucket: 'my-place-18dc3.appspot.com',
    iosClientId: '922332617982-eaea84qapkmj1tb6c1fjd79scep8s2kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPlaceAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQSI_yLwHHl1EB4wRCX2NSOrP9rYy4AY',
    appId: '1:922332617982:ios:2dd82729c3efb5706659af',
    messagingSenderId: '922332617982',
    projectId: 'my-place-18dc3',
    storageBucket: 'my-place-18dc3.appspot.com',
    iosClientId: '922332617982-eaea84qapkmj1tb6c1fjd79scep8s2kb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPlaceAdmin',
  );
}
